export const players = [
    {
        name: 'Emiliano',
        lastName: 'Martinez',
        age: 30,
        tShirtNumber: 23,
        currentClub: 'Aston Villa (ENG)',
        countryClub: 'ENGLAND',
        photo: 'emiliano-martinez',
        position: 0,
        isInside: false,

        yellowCard: 0
    },
    {
        name: 'Franco',
        lastName: 'Armani',
        age: 36,
        tShirtNumber: 1,
        currentClub: 'River Plate',
        countryClub: 'ARGENTINA',
        photo: 'franco-armani',
        position: 0,
        isInside: true,
        yellowCard: 0
    },
    {
        name: 'Gerónimo',
        lastName: 'Rulli',
        age: 30,
        tShirtNumber: 12,
        currentClub: 'Villarreal',
        countryClub: 'SPAIN',
        photo: 'geronimo-rulli',
        position: 0,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Marcos',
        lastName: 'Acuna',
        age: 30,
        tShirtNumber: 8,
        currentClub: 'Sevilla',
        countryClub: 'SPAIN',
        photo: 'marcos-acuña',
        position: 1,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Juan',
        lastName: 'Foyth',
        age: 24,
        tShirtNumber: 2,
        currentClub: 'Villarreal',
        countryClub: 'SPAIN',
        photo: 'juan-foyth',
        position: 1,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Lisandro',
        lastName: 'Martinez',
        age: 24,
        tShirtNumber: 25,
        currentClub: 'Manchester United',
        countryClub: 'ENGLAND',
        photo: 'lisandro-martinez',
        position: 1,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Nahuel',
        lastName: 'Molina',
        age: 24,
        tShirtNumber: 26,
        currentClub: 'Atletico Madrid',
        countryClub: 'SPAIN',
        photo: 'nahuel-molina',
        position: 1,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Gonzalo',
        lastName: 'Montiel',
        age: 25,
        tShirtNumber: 4,
        currentClub: 'Sevilla',
        countryClub: 'SPAIN',
        photo: 'gonzalo-montiel',
        position: 1,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Nicolás',
        lastName: 'Otamendi',
        age: 34,
        tShirtNumber: 19,
        currentClub: 'Benfica',
        countryClub: 'PORTUGAL',
        photo: 'nicolas-otamendi',
        position: 1,
        isInside: false, yellowCard: 1
    },
    {
        name: 'Germán',
        lastName: 'Pezzella',
        age: 31,
        tShirtNumber: 6,
        currentClub: 'Real Betis',
        countryClub: 'SPAIN',
        photo: 'german-pezzella',
        position: 1,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Cristian',
        lastName: 'Romero',
        age: 24,
        tShirtNumber: 13,
        currentClub: 'Tottenham',
        countryClub: 'ENGLAND',
        photo: 'cristian-romero',
        position: 1,
        isInside: false, yellowCard: 1
    },
    {
        name: 'Nicolás',
        lastName: 'Tagliafico',
        age: 30,
        tShirtNumber: 3,
        currentClub: 'Lyon',
        countryClub: 'FRANCE',
        photo: 'nicolas-tagliafico',
        position: 1,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Rodrigo',
        lastName: 'De Paul',
        age: 28,
        tShirtNumber: 7,
        currentClub: 'Atletico Madrid',
        countryClub: 'SPAIN',
        photo: 'rodrigo-de-paul',
        position: 2,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Enzo',
        lastName: 'Fernandez',
        age: 21,
        tShirtNumber: 24,
        currentClub: 'Benfica',
        countryClub: 'PORTUGAL',
        photo: 'enzo-fernandez',
        position: 2,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Alejandro',
        lastName: 'Gómez',
        age: 34,
        tShirtNumber: 17,
        currentClub: 'Sevilla',
        countryClub: 'SPAIN',
        photo: 'alejandro-gomez',
        position: 2,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Alexis',
        lastName: 'Mac Allister',
        age: 23,
        tShirtNumber: 20,
        currentClub: 'Brighton',
        countryClub: 'ENGLAND',
        photo: 'alexis-mac-allister',
        position: 2,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Exequiel',
        lastName: 'Palacios',
        age: 24,
        tShirtNumber: 14,
        currentClub: 'Bayer Leverkusen',
        countryClub: 'GERMANY',
        photo: 'exequiel-palacios',
        position: 2,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Leandro',
        lastName: 'Paredes',
        age: 28,
        tShirtNumber: 5,
        currentClub: 'Juventus',
        countryClub: 'ITALY',
        photo: 'leandro-paredes',
        position: 2,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Guido',
        lastName: 'Rodríguez',
        age: 28,
        tShirtNumber: 18,
        currentClub: 'Real Betis',
        countryClub: 'SPAIN',
        photo: 'guido-rodriguez',
        position: 2,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Julián',
        lastName: 'Alvarez',
        age: 22,
        tShirtNumber: 9,
        currentClub: 'Manchester City',
        countryClub: 'ENGLAND',
        photo: 'julian-alvarez',
        position: 3,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Joaquín',
        lastName: 'Correa',
        age: 28,
        tShirtNumber: 16,
        currentClub: 'Inter Milan',
        countryClub: 'ITALY',
        photo: '',
        position: 3,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Ángel',
        lastName: 'Di María',
        age: 34,
        tShirtNumber: 11,
        currentClub: 'Juventus',
        countryClub: 'ITALY',
        photo: 'angel-di-maria',
        position: 3,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Paulo',
        lastName: 'Dybala',
        age: 28,
        tShirtNumber: 21,
        currentClub: 'AS Roma',
        countryClub: 'ITALY',
        photo: 'paulo-dybala',
        position: 3,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Nicolás',
        lastName: 'González',
        age: 24,
        tShirtNumber: 15,
        currentClub: 'Fiorentina',
        countryClub: 'ITALY',
        photo: '',
        position: 3,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Lautaro',
        lastName: 'Martinez',
        age: 25,
        tShirtNumber: 22,
        currentClub: 'Inter Milan',
        countryClub: 'ITALY',
        photo: 'lautaro-martinez',
        position: 3,
        isInside: false,
        yellowCard: 0
    },
    {
        name: 'Lionel',
        lastName: 'Messi',
        age: 35,
        tShirtNumber: 8,
        currentClub: 'PSG',
        countryClub: 'FRANCE',
        photo: 'lionel-messi',
        position: 3,
        isInside: false,
        yellowCard: 0
    }
];